ARG CKAN_IMAGE
FROM ${CKAN_IMAGE}

## Supervisor config
COPY supervisor/*.conf /etc/supervisord.d

## Cron jobs config
COPY setup/dbca_ckan_cron_jobs $APP_DIR
RUN chmod -x $APP_DIR/dbca_ckan_cron_jobs
RUN crontab -u ckan $APP_DIR/dbca_ckan_cron_jobs
